spring.application.name=OrderFoodSystem

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# DATABASE (read from ENV)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SERVER
server.port=${PORT:8080}
server.address=0.0.0.0

# VNPay
vnpay.tmnCode=${VNPAY_TMN_CODE}
vnpay.hashSecret=${VNPAY_HASH_SECRET}
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# SẼ SỬA SAU KHI DEPLOY BACKEND
vnpay.returnUrl=${VNPAY_RETURN_URL}
vnpay.ipnUrl=${VNPAY_IPN_URL}